import os
import sys
import subprocess
import json
from pathlib import Path

class CodeReviewer:
    """
    AutoAgent-TW AI Reviewer Engine (Phase 129)
    負責提取變更並生成審查意見。
    """
    def __init__(self, workspace_path="z:/autoagent-TW"):
        self.workspace = Path(workspace_path)
        self.report_path = self.workspace / "REVIEW-REPORT.md"

    def get_staged_diff(self):
        """獲取已暫存或最近一次 commit 的變更"""
        try:
            # 優先獲取未 commit 的變更，如果沒有則獲取最後一次 commit
            diff = subprocess.check_output(
                ["git", "diff", "--staged"], cwd=self.workspace
            ).decode("utf-8")
            if not diff:
                diff = subprocess.check_output(
                    ["git", "diff", "HEAD~1..HEAD"], cwd=self.workspace
                ).decode("utf-8")
            return diff
        except Exception as e:
            return f"Error fetching diff: {str(e)}"

    def generate_mock_report(self, diff_content):
        """
        模擬 AI 審查報告（實際環境中這部分會由 Antigravity 透過 Prompt 產生）
        """
        issues = []
        if "TODO" in diff_content:
            issues.append("| Medium | Code Quality | Found unfinished TODO in code |")
        
        if "password" in diff_content.lower() or "secret" in diff_content.lower():
            issues.append("| Critical | Security | Potential hardcoded credential detected |")

        report = f"""# AI Code Review Report (Phase 129)

## Summary
- **Status**: {"APPROVED" if not issues else "REQUEST CHANGES"}
- **Risk Level**: {"Low" if not issues else "High"}

## Issues Found
| Severity | Category | Description |
| :--- | :--- | :--- |
{chr(10).join(issues) if issues else "| - | - | No issues found |"}

---
*Generated by AutoAgent-TW AI Reviewer*
"""
        with open(self.report_path, "w", encoding="utf-8") as f:
            f.write(report)
        return self.report_path

if __name__ == "__main__":
    reviewer = CodeReviewer()
    diff = reviewer.get_staged_diff()
    path = reviewer.generate_mock_report(diff)
    print(f"[OK] Review report generated: {path}")
