"""
AutoAgent-TW Context Guard (Phase 123: Active Context Defense)
==============================================================
前置掃描工具 — 在 /aa-plan 執行前自動檢查並生成 .geminiignore。

用途：
  1. 掃描工作區中 >500KB 的非原始碼檔案
  2. 若 .geminiignore 不存在 → 自動生成
  3. 若已存在 → 驗證是否涵蓋已知地雷，回報缺漏
  4. 輸出預估 token 佔用量

安全設計：
  - 只讀掃描，不修改任何原始碼
  - .geminiignore 產生前會列出完整內容供使用者確認
  - 不會刪除任何檔案
"""

import os
import sys
import subprocess
from pathlib import Path

# 導入 Phase 128 記憶體哨兵
try:
    from auto_summarizer import MemorySentinel
except ImportError:
    MemorySentinel = None

# === 預設忽略規則模板 ===
DEFAULT_GEMINIIGNORE = """# === AutoAgent-TW Active Context Defense (ACD) ===
# Auto-generated by context_guard.py — Phase 123
# Purpose: Prevent Max Token Limit Error

# Build Artifacts
cli.js
cli.js.map
*.min.js
*.min.css
*.js.map
dist/
build/

# Dependencies & Virtual Environments
node_modules/
vendor/
venv/
.venv/
__pycache__/
*.pyc
*.pyd
*.dll
*.so
*.dylib
*.exe
*.whl
*.egg

# Large / Non-Source Files
temp/
logs/
*.log
*.sqlite
*.db
*.tar.gz
*.zip
*.rar

# IDE & OS
.vscode/
.idea/
.DS_Store
Thumbs.db
*.tmp

# Media
*.pdf
*.png
*.jpg
*.jpeg
*.gif

# Guardian temp
_guard_scan.py
""".strip()

# === 已知高風險副檔名 ===
BINARY_EXTENSIONS = {
    '.pyd', '.dll', '.so', '.dylib', '.exe', '.whl', '.egg',
    '.tar', '.gz', '.zip', '.rar', '.7z',
    '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.ico', '.svg',
    '.pdf', '.doc', '.docx', '.xls', '.xlsx',
    '.sqlite', '.db', '.pyc', '.pyo',
    '.map',
}

# === 已知應忽略的目錄 ===
IGNORE_DIRS = {
    'node_modules', 'vendor', 'venv', '.venv', '__pycache__',
    'dist', 'build', '.git', '.idea', '.vscode', 'temp', 'logs',
}


def scan_workspace(workspace_path: str) -> dict:
    """掃描工作區，回傳統計資訊與大型檔案清單。"""
    stats = {
        'total_files': 0,
        'total_size': 0,
        'large_files': [],       # > 500KB
        'source_files': 0,
        'source_size': 0,
        'binary_files': 0,
        'binary_size': 0,
    }

    source_exts = {'.py', '.ts', '.js', '.md', '.json', '.yaml', '.yml', '.toml', '.cfg', '.txt', '.html', '.css'}

    for root, dirs, files in os.walk(workspace_path):
        # 排除已知目錄（加速掃描）
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

        for f in files:
            filepath = os.path.join(root, f)
            try:
                size = os.path.getsize(filepath)
            except OSError:
                continue

            stats['total_files'] += 1
            stats['total_size'] += size
            ext = Path(f).suffix.lower()

            if ext in source_exts and size < 1_000_000:
                stats['source_files'] += 1
                stats['source_size'] += size
            elif ext in BINARY_EXTENSIONS or size > 500_000:
                stats['binary_files'] += 1
                stats['binary_size'] += size
                if size > 500_000:
                    stats['large_files'].append({
                        'path': os.path.relpath(filepath, workspace_path),
                        'size_mb': round(size / 1_048_576, 2),
                    })

    # 依大小排序
    stats['large_files'].sort(key=lambda x: x['size_mb'], reverse=True)
    return stats


def check_geminiignore(workspace_path: str) -> bool:
    """檢查 .geminiignore 是否存在。"""
    return os.path.exists(os.path.join(workspace_path, '.geminiignore'))


def generate_geminiignore(workspace_path: str) -> str:
    """生成 .geminiignore 檔案。回傳檔案路徑。"""
    target = os.path.join(workspace_path, '.geminiignore')
    with open(target, 'w', encoding='utf-8') as f:
        f.write(DEFAULT_GEMINIIGNORE)
    return target


def estimate_tokens(source_size_bytes: int) -> int:
    """粗估 token 數量（1 token ≈ 4 bytes for English, 2 bytes for CJK）。"""
    # 保守估計：混合語言取 3 bytes/token
    return source_size_bytes // 3


def run_guard(workspace_path: str = None):
    """主進入點：執行完整 Context Guard 流程。"""
    # 強制 UTF-8 輸出，避免 Windows cp950 編碼 crash
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

    if workspace_path is None:
        workspace_path = os.getcwd()

    print("=" * 50)
    print("  AutoAgent-TW Context Guard v1.0")
    print("  Phase 123: Active Context Defense")
    print("=" * 50)
    print(f"\nScanning: {workspace_path}")

    # Step 1: 掃描
    stats = scan_workspace(workspace_path)
    print(f"\n--- Workspace Statistics ---")
    print(f"  Total files:  {stats['total_files']:,}")
    print(f"  Total size:   {stats['total_size'] / 1_048_576:.1f} MB")
    print(f"  Source files:  {stats['source_files']:,} ({stats['source_size'] / 1_048_576:.1f} MB)")
    print(f"  Binary/Large: {stats['binary_files']:,} ({stats['binary_size'] / 1_048_576:.1f} MB)")

    # Step 2: 大型檔案警告
    if stats['large_files']:
        print(f"\n[WARN] Found {len(stats['large_files'])} files > 500KB:")
        for lf in stats['large_files'][:10]:
            print(f"    {lf['size_mb']:>8.2f} MB  {lf['path']}")
        if len(stats['large_files']) > 10:
            print(f"    ... and {len(stats['large_files']) - 10} more")

    # Step 3: Token 預估
    est_tokens = estimate_tokens(stats['source_size'])
    print(f"\n--- Token Estimate (source only) ---")
    print(f"  Estimated: ~{est_tokens:,} tokens")
    if est_tokens > 100_000:
        print(f"  [DANGER] Exceeds safe threshold (100K). ROADMAP pruning recommended.")
    elif est_tokens > 50_000:
        print(f"  [WARN] Approaching limit. Monitor carefully.")
    else:
        print(f"  [OK] SAFE: Within normal operating range.")

    # Step 5: 記憶體哨兵檢查 (Phase 128 Integration)
    if MemorySentinel:
        print(f"\n--- Persistent Memory Check ---")
        sentinel = MemorySentinel(threshold=50000)
        # 針對 current.md 所在的實際路徑進行探測
        project_root = os.getcwd()
        basename = os.path.basename(project_root)
        current_md_path = os.path.join(project_root, f".context-{basename}", "current.md")
        
        sentinel.target_file = current_md_path
        exit_code = sentinel.check()
        
        if exit_code == 2:
            print(f"  [OVERLOAD] L1 Memory (current.md) exceeds threshold!")
            print(f"  >>> ACTION: Requesting Antigravity to perform Delegated Summary.")
        else:
            print(f"  [OK] L1 Memory is healthy.")

    print(f"\n{'=' * 50}")
    print(f"  Context Guard scan complete.")
    print(f"{'=' * 50}")

    return stats


if __name__ == '__main__':
    target = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    run_guard(target)

