import json
import time
import subprocess
import os
import sys
from pathlib import Path
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger

# Path setup
PROJECT_ROOT = Path(__file__).resolve().parent.parent
STATE_DIR = PROJECT_ROOT / ".agent-state"
TASKS_FILE = STATE_DIR / "scheduled_tasks.json"
LOG_DIR = PROJECT_ROOT / ".agents" / "logs"
LOG_FILE = LOG_DIR / "scheduler.log"

STATE_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

def log_message(msg):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted = f"[{timestamp}] {msg}"
    print(formatted)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(formatted + "\n")

def execute_task(task_id, cmd):
    log_message(f"Starting scheduled task: {task_id} :: CMD: {cmd}")
    try:
        # Wrap the command as it might be a single string 'aa-help' etc.
        # Use full path for python scripts if needed.
        process = subprocess.Popen(
            cmd,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=PROJECT_ROOT
        )
        stdout, stderr = process.communicate()
        
        if process.returncode == 0:
            log_message(f"Task {task_id} completed successfully.")
        else:
            log_message(f"Task {task_id} failed with exit code {process.returncode}. Error: {stderr}")
            # Potentially update status notifier for v1.5.0 dashboard integration
            update_dashboard(f"Scheduled Task {task_id} FAILED", "Manual Investigation Required", "fail")
            
    except Exception as e:
        log_message(f"Exception during task {task_id} execution: {e}")

def update_dashboard(task_name, next_goal, status):
    # Integration with v1.5.0 status-notifier
    updater_script = PROJECT_ROOT / ".agents" / "skills" / "status-notifier" / "scripts" / "status_updater.py"
    if updater_script.exists():
        subprocess.run([
            sys.executable, str(updater_script),
            "--task", f"Scheduler: {task_name}",
            "--next", next_goal,
            "--status", status,
            "--logs", f"Event generated by AutoAgent Scheduler Daemon"
        ])

class SchedulerDaemon:
    def __init__(self):
        self.scheduler = BackgroundScheduler()
        self.last_mtime = 0
        self.jobs = {} # task_id -> apscheduler job object

    def sync_tasks(self):
        if not TASKS_FILE.exists():
            return

        mtime = os.path.getmtime(TASKS_FILE)
        if mtime > self.last_mtime:
            log_message("Detected changes in scheduled_tasks.json, reloading...")
            self.last_mtime = mtime
            self._reload_tasks()

    def _reload_tasks(self):
        try:
            with open(TASKS_FILE, "r", encoding="utf-8") as f:
                current_tasks = json.load(f)

            active_ids = set()
            for task in current_tasks:
                task_id = task.get("id")
                active_ids.add(task_id)
                
                # If job already exists, remove it first to handle potential changes in trigger
                if task_id in self.jobs:
                    self.scheduler.remove_job(task_id)
                
                trigger_type = task.get("trigger_type", "interval")
                params = task.get("params", {})
                command = task.get("command", "")

                if trigger_type == "cron":
                    trigger = CronTrigger(**params)
                elif trigger_type == "interval":
                    # minute=1, hours=2 etc.
                    trigger = IntervalTrigger(**params)
                else:
                    log_message(f"Unknown trigger type {trigger_type} for task {task_id}")
                    continue

                job = self.scheduler.add_job(
                    execute_task,
                    trigger,
                    id=task_id,
                    args=[task_id, command],
                    name=task.get("name", task_id),
                    replace_existing=True
                )
                self.jobs[task_id] = job
                log_message(f"Scheduled task {task_id}: {task.get('name')} via {trigger_type} ({params})")

            # Clean up old jobs no longer in config
            for jid in list(self.jobs.keys()):
                if jid not in active_ids:
                    self.scheduler.remove_job(jid)
                    del self.jobs[jid]
                    log_message(f"Removed task {jid}")

        except Exception as e:
            log_message(f"Error reloading tasks: {e}")

    def run(self):
        log_message("AutoAgent-TW Scheduler Daemon starting...")
        self.scheduler.start()
        log_message("Daemon is active. Press CTRL+C to terminate.")
        
        try:
            while True:
                self.sync_tasks()
                time.sleep(10) # check for config changes every 10s
        except (KeyboardInterrupt, SystemExit):
            self.scheduler.shutdown()
            log_message("Daemon stopped.")

if __name__ == "__main__":
    daemon = SchedulerDaemon()
    daemon.run()
